
# @name get-prompts
GET http://localhost:3000/prompts

###

# @name uploadVideo
POST http://localhost:3000/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="exemplo.mp3"
Content-Type: audio/mpeg

< ./exemplo.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST http://localhost:3000/videos/4d03b683-ab7d-4773-921e-46a772c08c58/transcription
Content-Type: application/json

{
  "prompt": "VidTextAI"
}

###

# @name generate-ai-completion
POST http://localhost:3000/ai/complete
Content-Type: application/json

{
  "videoId": "4d03b683-ab7d-4773-921e-46a772c08c58",
  "temperature": 0.5,
  "template": "Gere um resumo sucinto da transcrição do vídeo informado a seguir: '''{transcription}'''"
}

###

# @name login
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "mls.aprendizagem@gmail.com",
  "passwordHash": "d2a92bbdd3c9702679b10ae0d75f2b9a3ec859a9ab403df74e0eaeb055cf5f4e"
}

